overblog_graphql:
  definitions:
    auto_compile: true
    use_classloader_listener: true
    cache_dir: "%kernel.project_dir%/var/cache/graphql/types"
    schema:
      query: Query
    mappings:
      auto_discover: true
      types:
        -
            type: yaml
            dir: "%kernel.project_dir%/config/graphql/types"
            suffix: null
