nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
        paths:
            '^/api':
                allow_origin: ['*']
                allow_headers: ['*']
                allow_methods: ['GET']
                max_age: 3600
            '^/':
                allow_origin: ['*']
                allow_headers: ['*']
                allow_methods: ['POST']
                max_age: 3600