Query:
  type: object
  config:
    description: "Character Repository"
    fields:
      character:
        type: "Character"
        args:
            isMostAppeared:
              description: "Show most appeared character"
              type: "Boolean"
        resolve: "@=resolver('Character', [args])"
      species:
        type: "[Species]"
        args:
            isMostAppeared:
              description: "Show species appeared in most films"
              type: "Boolean"
        resolve: "@=resolver('Species', [args])"
